sudo: required
# tell travis that we need docker
services:
  - docker

before_install:
  - docker build -t hamzaabamboo/docker-react-thing -f Dockerfile.dev .

script:
  - docker run hamzaabamboo/docker-react-thing npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react-udemy-thing"
  env: "DockerReactUdemyThing-env"
  bucket_name: "elasticbeanstalk-us-east-2-072979993612"
  bucket_path: "docker-react-udemy-thing"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
