sudo: required
# tell travis that we need docker
services:
  - docker

before_install:
  - docker build -t hamzaabamboo/docker-react-thing -f Dockerfile.dev .

script:
  - docker run hamzaabamboo/docker-react-thing npm run test -- --coverage
